; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
lib_deps = 
	lvgl/LVGL@^8.3.11
	moononournation/GFX Library for Arduino@1.4.9
build_flags = 
	-D LVGL_DISPLAY_WIDTH=480
	-D LVGL_DISPLAY_HEIGHT=480
	-D BOARD_HAS_PSRAM
	-I include
monitor_speed = 115200
